theparanoids/crypki

.travis.yml
README.md

**Issue #, if available:**
**Description of changes:**
Adding travis build job.

adding basic travis job

---

README.md

fix a small typo

---

README.md

**Issue #, if available:**
Removing redundant "crypki" header from README
**Description of changes:**

remove redundant header

---

go.sum
proto/mock/mock.go
proto/protogen.go

regen mocks

---

.travis.yml
README.md
api/blob.go
api/sign.go
api/sshhost.go
api/sshuser.go
api/x509cert.go
codecov.yml
config/config.go
x509cert/encode.go
x509cert/x509.go

enable race detector, coverage and fix lint issues

---

api/blob.go
api/sign_test.go
crypki.go
pkcs11/signer.go
pkcs11/signer_test.go

**Issue #, if available:**
**Description of changes:**
- rename `Sign` to `SignBlob` for clarity
- implement `GetBlobSigningPublicKey` and `SignBlob`
- add unit tests for `GetBlobSigningPublicKey` and `SignBlob`

implement SignBlob and GetBlobSigningPublicKey

---

README.md

Fixes https://github.com/yahoo/crypki/issues/10

fix config link

---

config/config.go
config/config_test.go
config/testdata/testconf-good.json

fix whitelist check for endpoints

---

docker-softhsm/crypki.conf.sample
docker-softhsm/init_hsm.sh
pkcs11/ecdsa.go
pkcs11/p11signer_test.go
pkcs11/signer.go

add support for signing with ECDSA P256 key

---

docker-softhsm/init_hsm.sh
pkcs11/ecdsa.go

- added support for P-224, P-256, P-384 and P-521

support additional curves

---

.travis.yml

Publish crypki binary and sha256 on every release

---

README.md
docker-softhsm/crypki.conf.sample
docker-softhsm/init_hsm.sh
docker-softhsm/sign_blob.json
go.mod
go.sum

Also add sign blob config in local docker

bump up grpc-go version which fixes http2 DoS vulns

---

server/server.go

Fixes https://github.com/yahoo/crypki/issues/32 and https://github.com/yahoo/crypki/issues/33 

honor client auth mode specified in config

---

README.md

rename yahoo -> theparanoids

---

pkcs11/signer.go

Explain pkcs11/signer.login

---

proto/protogen.go
proto/sign.pb.go

regen  proto files with newer protobuf

---

config/config.go
config/config_test.go
config/testdata/testconf-bad-duplicate-identifier.json
config/testdata/testconf-bad-non-specify-identifier.json
config/testdata/testconf-bad-non-specify-pin-path.json
config/testdata/testconf-bad-non-specify-x509-ca-cert-path.json
config/testdata/testconf-bad-non-x509-cert-for-x509-endpoint.json
config/testdata/testconf-bad-same-slot-different-pin-path.json
config/testdata/testconf-bad-unknown-identifier.json
config/testdata/testconf-bad-unsupported-key-type.json
config/testdata/testconf-good.json
docker-softhsm/crypki.conf.sample

Remove TLSServerName as it is not in use

---

.github/dependabot.yml

add dependabot yml to enable automated PRs for package upgrades

---

.github/dependabot.yml

add dependabot config for action updates

---

crypki.go

make ST and L fields in CA certificate optional

---

x509cert/x509.go
x509cert/x509_test.go

GenCACert - do not set fields with empty value

---

api/sshhost_test.go
go.mod

remove github.com/golang/protobuf dep

---

pkcs11/signer.go

This PR adds additional logging to check time taken by request to get signer from the signerpool.

add log for time taken to fetch signer from pool

---

server/interceptor/access_log_interceptor_test.go

This PR is a follow-up of #105 and #106
To fix: https://github.com/theparanoids/crypki/runs/3458074447?check_suite_focus=true

fix go-lint failure

---

server/interceptor/access_log_interceptor_test.go
server/server.go

fix codeql warning

---

.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yml
.github/workflows/license.yml
.github/workflows/linux.yml
.github/workflows/release.yml
api/log.go
api/log_test.go
docker-softhsm/Dockerfile
docker-softhsm/gen-crt.sh
docker-softhsm/init_hsm.sh
gen.sh
keyid.go
pkcs11/ecdsa.go
pkcs11/login.go
pkcs11/login_test.go
pkcs11/p11signer_test.go
pkcs11/rsa.go
pkcs11/signer.go
pkcs11/signer_test.go
pkcs11/signerpool_test.go
server/interceptor/access_log_interceptor.go
server/interceptor/access_log_interceptor_test.go
server/interceptor/interceptor.go
server/interceptor/interceptor_test.go
server/interceptor/shutdown.go

- add license header to files that didn't have it
- add license check github action

license fixes

---

.github/workflows/license.yml

fix yml - 2

---

.github/workflows/license.yml

fix yml - 3

---

server/server.go

When we have multiple identifiers per endpoint, we need to create only 1 scheduler per endpoint as 1 identifier is active at a time. This change ensures schedulers are started per endpoint and not per identifier.

ensure only 1 instance of scheduler is started per endpoint

---

config/config.go

fix SignatureAlgo range

---

pkcs11/work.go

cleanup extra log message

---

pkcs11/signer.go
server/scheduler/priority.go
server/scheduler/workerpool.go

This PR removes redundant and not useful logging.

cleanup logging

---

pkcs11/work.go

In case there is a timeout when fetching signer from the signerpool, we should increment the appropriate counter for logging purposes.

increment counter in case of timeout

---

README.md
cmd/gen-cacert/main.go
docker-softhsm/init_hsm.sh

Give an example of gen-cacert usage. Also sync `gen-cacert/main.go` from yahoo internal repo.

update readme for gen-cacert

---

README.md

add openssf best practices badge

---

api/blob.go
api/sshhost.go
api/sshuser.go
api/x509cert.go

log key identifier

---

go.mod
go.sum
server/interceptor/access_log_interceptor_test.go

remove useless dependency: testify

---

.github/workflows/depsreview.yml

add dependency review action

---

.github/workflows/scorecards.yml

fix scorecard failure

---

docker-softhsm/Dockerfile
docker-softhsm/init_hsm.sh

update softhsm module path and update golang version

---

.github/workflows/reuse.yml

add support for sign/publish docker image with sbom

---

docker-softhsm/Dockerfile

update golang version to 1.20.6 in Dockerfile

---

.goreleaser.yml

only build amd64 and arm64

---

.goreleaser.yml

enable cgo as required for pkcs11 lib

---

.goreleaser.yml

enable only amd64 for now

---

.goreleaser.yml

enable only amd64 for container images

---

.goreleaser.yml

use a base image which has glibc

---

.github/workflows/release.yml
.goreleaser.yml
Dockerfile

use dockers field in goreleaser

---

.goreleaser.yml

fix container signing
