theparanoids/crypki

- README.md
PR removes `go install` command in the README installation instruction as it is redundant with `go get` (which fetches and installs the given package).
> remove `go install` - redundant with `go get`

- .travis.yml
https://docs.travis-ci.com/user/deployment/releases/ says:
> Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created during the build, which will probably delete what you are trying to upload.
@maditya 
> add skip_cleanup for deploy travis step

- docker-softhsm/crypki.conf.sample
The tabs seemed to be mixed up in the sample configuration file, so I have changed them to spaces.
***
> Indent with spaces instead of tabs

- config/config.go
- config/config_test.go
- server/server.go
I want to restrict listen addr like 'localhost'. It is helpful in cases like working with proxy e.g. nginx.
(Access control is assumed to be done by proxy instead of crypki's mtls.)
The default setting is the same as before.
> add tlshost option

- .github/workflows/linux.yml
- .github/workflows/release.yml
I have matched GitHub Actions versions we use to the same one in linux and release workflows.
***
> GitHub Actions versions we use to the same one

- api/blob.go
- api/log.go
- api/log_test.go
- api/sign.go
- api/sshhost.go
- api/sshuser.go
- api/x509cert.go
After #35, if the server panics, we return `codes.Internal` to client in `grpc.UnaryInterceptor`. However, we still log the "default status code" (e.g. 201 for [PostX509Certificate](https://github.com/theparanoids/crypki/blob/ac66b39615ccb28407203c7566c53f2351e42b9c/api/x509cert.go#L76)) instead of 500, and this PR aims to solve the inconsistency.
> Log the correct status code when panic

- api/blob.go
- api/log.go
- api/log_test.go
- api/sshhost.go
- api/sshuser.go
- api/x509cert.go
`logWithCheckingPanic()` output incorrect statusCode and error now.
Because the function arguments are evaluated as usual. (ref. https://golang.org/ref/spec#Defer_statements
( playground sample: https://play.golang.org/p/IJ2amM417mC )
This PR change the function argument to pass-by-reference to fix it.
Additionally i added a test in case of the error without panic.
> Fix log when error is occurred without panic

- config/config.go
- config/config_test.go
- config/testdata/testconf-good.json
- server/interceptor.go
- server/interceptor_test.go
- server/server.go
This PR adds a new feature (default to be disabled and can be enabled through config) to shutdown the server when the underlying signing service fails to handle signing requests too frequently. Once the feature is enabled, the server could be shutdown when one of  the following conditions meets:
* when the server fails to handle signing requests 4 times in a row, or
* when the server fails to handle signing requests 10 times within 1 minutes.
We assume the signing service returns internal service error when the operation fails. Therefore, a grpc interceptor is injected to monitor the returned status code.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
> Shutdown on frequent internal service error

- config/config.go
- config/config_test.go
- config/testdata/testconf-good.json
- server/interceptor/interceptor.go
- server/interceptor/interceptor_test.go
- server/interceptor/shutdown.go
- server/interceptor_test.go
- server/server.go
This PR follows #45 to
1. Change the names `ShutdownOnFrequentSigningFailure` and `ShutdownOnSigningFailureCriteria` to `ShutdownOnInternalFailure` and `ShutdownOnInternalFailureCriteria`, respectively.
2. Add `ReportMode` that disables the shutdown operation, but still reports such events through logging.
3. Create `server/interceptor` package and update APIs (export methods, add context into the function signature, etc.)
> Improved naming and logging for shutdown-on-internal-failure feature

- .github/workflows/linux.yml
Go 1.15 is out in this week. It's added into the matrix for tests.
***
> Testing on Go 1.15

- config/config.go
- config/config_test.go
- config/testdata/testconf-good.json
- server/server.go
To fulfill a request, the HSM may take more than 10 seconds, which is the currently hard-coded value for `WriteTimeout`. Consequently, the client would receive the following error in such scenario.
```
code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR
```
> Make timeouts configurable

- cmd/gen-cacert/main.go
- config/config.go
- config/config_test.go
- crypki.go
- pkcs11/signer.go
- x509cert/x509.go
This PR enables a user to generate a CA cert with a configurable validity period.
The validity period would be 2 years if it is not specified in the configuration file.
> make CA cert validity period configurable

- api/blob.go
- api/sign_test.go
- api/sshhost.go
- api/sshuser.go
- api/x509cert.go
- api/x509cert_test.go
- cmd/gen-cacert/main.go
- config/config.go
- crypki.go
- pkcs11/signer.go
- pkcs11/signer_test.go
- pkcs11/signerpool.go
- pkcs11/signerpool_test.go
- server/server.go
This PR is to address high latency issue when there is a sudden spike in client requests. Due to the high latency issue, we see lot of client request timing out/canceled but the server still processes those requests which is a waste effort.
There are potentially 2 bottlenecks for increase in latency:
1. Currently we have limit on the poolsize of signers to 25 and each signer makes a request to HSM for signing the cert. During the spike in requests, we see the number of requests increasing exponentially and the server spending lot of time waiting for a signer from the pool. This causes the increase in latency as it is waiting ideally for a signer to make a request to HSM. 
2. HSM should always take a fixed amount of time to sign the request regardless of the load. (On an avg, if the key is …
> Cancel server request when client cancels

- api/sshhost.go
- api/sshhost_test.go
- api/sshuser.go
- api/sshuser_test.go
- api/x509cert.go
- api/x509cert_test.go
- pkcs11/signer.go
The changes in this PR are targeted to address high latency when number of client requests increase exponentially. Due to high latency, we see a lot of requests being cancelled by the client but the server still processes causing the server spending a lot of time waiting for signer from the pool. 
As part of this PR we ensure that if the client has cancelled the request or timeout has occurred before server makes a request to HSM to sign a certificate the request will be cancelled. 
The change is made for request type: SSHUserCert & SSHHostCert for both signing SSH certificate and also getting SSH Certificate Key.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …
> Cancel server requests when client cancels - part 2 (SSH Cert)

- api/x509cert.go
- api/x509cert_test.go
The changes in this PR are targeted to address the high latency when number of client requests increases exponentially due to retry. Due to the high latency, a lot of requests are cancelled by the client, but the server still tries to process them in the current setup, which causes the server to spend a lot of time waiting for a signer from the pool.
As part of this PR, we ensure that if the client has cancelled the request, or timeout has occurred before the server makes a request to HSM to get a certificate, the request will be cancelled.
A similar code change has been applied to `PostX509Certificate` in #56, and this PR caters for `GetX509CACertificate`.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree …
> Add support for getting signed x509 cert

- api/blob_test.go
- cmd/gen-cacert/main.go
- pkcs11/login.go
- pkcs11/signer.go
- pkcs11/signer_test.go
- pkcs11/signerpool_test.go
- server/server.go
- x509cert/encode_test.go
This PR replaces use of ioutil.Discard with io.Discard & ioutil.ReadFile/ioutil.WriteFile with the corr. os package functions ReadFile & WriteFile. This change is done as part of the upgrade of go version to 1.16.
> replace use of ioutil with io/os as part of 1.16 upgrade

- docker-softhsm/Dockerfile
- pkcs11/signer.go
This PR consists of changes for adding more info in comments when there is a mismatch in signature algo. It also simplifies the check in isValidCert method.
> Add detailed error comments when mismatch in signature algo

- .gitignore
- Contributing.md
- gen.sh
PR adds `gen.sh` to install tool binaries automatically without side-effects. One can still use `go generate` without `gen.sh` if he/she prefers to install the tool binaries manually somehow.
> Add gen.sh to install tool binaries automatically

- pkcs11/signer.go
- pkcs11/signer_test.go
When fetching x509 ca cert, we fetch the cert from filesystem and we do not need to make an extra call to HSM. This PR fixes that issue.
> remove extra hsm call when getting x509 ca cert

- server/interceptor/access_log_interceptor.go
- server/interceptor/access_log_interceptor_test.go
- server/server.go
This PR implements logger interceptor to log the time and the cname of the peering client cert when a request arrives at crypki server.
Also, PR uses [bufferConn](https://pkg.go.dev/google.golang.org/grpc/test/bufconn) to set up an in-memory grpc server for unit tests.
--
> implement logger interceptor

- api/blob.go
- api/sign_test.go
- api/sshhost.go
- api/sshuser.go
- crypki.go
- pkcs11/signer.go
- pkcs11/signer_test.go
This PR is a follow-up of #120 & #121. It supports priority based scheduling feature for signing SSH & Blob keys.
> Add priority scheduling feature for ssh & blob key signing

- crypki.go
- pkcs11/algosigner.go
- pkcs11/algosigner_test.go
- pkcs11/signer.go
- pkcs11/signer_test.go
With the latest OpenSSH & Mac update signature algo ssh-rsa is not supported. This change, uses the signature algo configured during server setup.
> Explicitly use signature algorithm for SSH certs

- cmd/gen-cacert/main.go
- config/config.go
- config/config_test.go
- config/testdata/testconf-bad-endpoints.json
- config/testdata/testconf-bad-unknown-signature-algo.json
- config/testdata/testconf-bad-unsupported-key-type.json
- config/testdata/testconf-good.json
- crypki.go
- pkcs11/algosigner.go
- pkcs11/algosigner_test.go
- pkcs11/ecdsa.go
- pkcs11/p11signer.go
- pkcs11/p11signer_test.go
- pkcs11/pkcs11.go
- pkcs11/rsa.go
- pkcs11/signer.go
- pkcs11/signer_test.go
- pkcs11/signerpool.go
- pkcs11/signerpool_test.go
- x509cert/x509.go
- x509cert/x509_test.go
This pull request uses the signature algorithm & public algorithm defined in the crypto library & removes the PublicAlgorithm & SignatureAlgorithm type from crypki. This change is backwards incompatible & the config needs to change in order to map the new values for PublicKeyAlgorithm & SignatureAlgorithm.
Mapping table:
| crypki Signature Algorithm value | Crypto library Signature Algorithm value |
| ------------------- | ----------------------------------- |
| SHA256WithRSA (1) | SHA256WithRSA(4) |
| ECDSAWithSHA256 (2) | ECDSAWithSHA256(10) |
| ECDSAWithSHA384 (3) | ECDSAWithSHA384(11) |
| SHA512WithRSA (4) | SHA512WithRSA(6) |
| SHA1WithRSA (5) | SHAWithRSA(3) |
| crypki Public Key Algorithm value | Crypto library Public Key Algorithm value |
| ------------------- | …
> change from using crypki.PublicKey/SignAlgo to x509.PublicKey/SignAlgo

- pkcs11/signer.go
- pkcs11/signer_test.go
This PR is to handle the case when server is not running, but user needs to generate a host cert or x509 ca cert.
> handle special case when server is not running

- config/config.go
Change default PKCS11 timeout from 5 second to 10 second as downstream request currently uses a higher timeout. In a follow up PR make this timeout configurable.
> change timeout

- docker-softhsm/gen-crt.sh
We are going to release RA (Registration Authority). To enable the mTLS between sshra container and crypki container, we add `crypki` to the SAN of tls server cert.
--
> add SAN `crypki` to tls server cert

- config/config.go
- pkcs11/signer.go
- pkcs11/signer_test.go
- pkcs11/work.go
- server/scheduler/worker.go
When client cancels the request, server needs to stop processing any pending request for that client. This PR also handles the case where the worker does not indefinitely wait for fetching the signer from signer pool by assigning a timeout to it.
> resolve potential deadlock

- pkcs11/signer_test.go
- pkcs11/work.go
- server/scheduler/worker.go
- server/scheduler/workerpool.go
- server/server.go
This PR cleans up reference of HSMTimeout with PKCS11Timeout and also cleans up misc code.
> Cleanup code

- README.md
- docker-softhsm/Dockerfile
- docker-softhsm/crypki.conf.sample
- docker-softhsm/gen-crt.sh
- docker-softhsm/init_hsm.sh
PR:
* switches ssh-user-cert endpoint to ec-prime384 for `docker-softhsm`
* export signing pubic key to path `slot_pubkeys_path` for users to extract ca keys easily
* compile `gen-cacert` in docker
> use ec384 for ssh-user-cert & export signing public key

- cmd/gen-cacert/main.go
- cmd/sign-x509cert/main.go
This PR adds sign-x509 cert standalone sign once support.
This can be used for signing a certificate signing request for server/client TLS certs.
eg: 
```
$ cat>tls_server_csr.conf<<EOF
[ req ]
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no
[ req_distinguished_name ]
C="US"
ST=CA
L=Sunnyvale
O=Yahoo
OU=Engineering
CN=test.yahoo.com
[ req_ext ]
subjectAltName=$(echo "DNS:${hosts}" | sed -e "s/,/,DNS:/g")
EOF
$ openssl genrsa -out tls_server.key 4096
$ openssl req -sha256 -new -config tls_server_csr.conf -key tls_server.key -nodes -out tls_server.csr
$ sudo ./sign-x509cert -config ca_config.cfg -days 730 -cacert ./tls_signing_ca.crt -in tls_server.csr
```
I confirm that this contribution is made under the terms of the license found in the root directory …
> add sign-x509cert

- api/blob.go
- api/sign_test.go
- api/sshhost.go
- api/sshuser.go
- api/x509cert.go
- cmd/gen-cacert/main.go
- cmd/sign-x509cert/main.go
- crypki.go
- pkcs11/signer.go
- pkcs11/signer_test.go
GET operation also requires signer for getting key info, we need to start supporting any get operation via worker instead of fetching the signer from pool directly. This PR is to lay a framework for eventually sending all get requests to worker.
> Add request chan to Get request for fetching certificates

- pkcs11/signer.go
- pkcs11/signer_test.go
- pkcs11/signerpool.go
- pkcs11/work.go
This PR contains the foll. changes:
1. Move the signing data logic to worker instead of client.
2. Handle cases when pkcs11 timeout or client cancel request.
3. Introduce HSM timeout to have an upper bound on hsm signing request
> Move signing of data to worker

- cmd/gen-cacert/main.go
- cmd/sign-x509cert/main.go
- pkcs11/signer.go
- server/server.go
- x509cert/x509.go
- x509cert/x509_test.go
typically Root CA certificates do not include IP addresses nor hostnames. So the PR introduces two command line options to skip the inclusion of hostname and IP addresses.
Most services are now utilizing spiffe URIs in server and root certificates. There is new -uri option for the gen-cacert utility that the admin can include a spiffe uri that will be included in the SAN field in the root ca certificate.
> cacert san field changes

- pkcs11/ecdsa.go
- pkcs11/rsa.go
- pkcs11/signer_test.go
- pkcs11/signerpool_test.go
both rsa and ecdsa support PublicKey access calls generate panics whenever pkcs11 call to HSM returns any type of error. This is bad since crypki is handling large number of requests and a panic call fails all those active requests. furthermore, all the instances pretty much get killed at the same time and we have a complete outage until systems restarts all instances. the process should not call panic and instead just return nil. all the std go library x.509 cert calls correctly handle when nil is passed for the public key and return an error.
this is particularly a major issue in AWS, where AWS periodically recycles the HSMs. Typically we've seen AWS recycle at least one of the HSMs in each of our clusters every week resulting a brief 5-10 min outage until all the instances are …
> remove panic calls from rsa/ecdsa public key methods

- .goreleaser.yml
To avoid this warning - 
```
WARNING: Image reference ghcr.io/theparanoids/crypki:fb90598 uses a tag, not a digest, to identify the image to sign.
This can lead you to sign a different image than the intended one. Please use a
digest (example.com/ubuntu@sha256:abc123...) rather than tag
(example.com/ubuntu:latest) for the input to cosign. The ability to refer to
images by tag will be removed in a future release.
```
> use digest instead of tag when invoking cosign sign

- api/log_test.go
Until further investigation is done, this will reduce flakiness in PR builds
> temporarily stop doing t.Parallel for tests with panic

- pkcs11/ecdsa.go
- pkcs11/login.go
- pkcs11/p11signer.go
- pkcs11/pkcs11.go
- pkcs11/work.go
> fix lint warnings

- .github/workflows/release.yml
`--rm-dist` is deprecated in favor of `--clean` - https://github.com/goreleaser/goreleaser/blob/main/www/docs/deprecations.md?plain=1#L497
> fix goreleaser

- otellib/http.go
To ensure we are always using the semconv v1.26.0 which aligns with the semconv version in `go.opentelemetry.io/otel/sdk@v1.32.0`. It avoids any conflicts when importing back to other projects.
> update otel semconv to 1.26
